version: "3.6"

services:
  account:
    build:
      context: "."
      dockerfile: "./account/Dockerfile"
    ports:
      - "8000:8080"
    depends_on:
      - "account_db"
    environment:
      DATABASE_URL: "postgres://spidey:123456@account_db/spidey?sslmode=disable"

  account_db:
    build:
      context: "./account"
      dockerfile: "Dockerfile-db"
    environment:
      POSTGRES_DB: "spidey"
      POSTGRES_USER: "spidey"
      POSTGRES_PASSWORD: "123456"
    restart: "unless-stopped"
